# Generated by Django 4.1.1 on 2022-09-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('kind', models.CharField(choices=[('rooms', 'Rooms'), ('experience', 'Experiences')], max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
