# Generated by Django 4.1.1 on 2022-09-26 18:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0002_room_category'),
        ('experiences', '0002_experience_category_alter_perk_details_and_more'),
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlists',
            new_name='Wishlist',
        ),
    ]
